//! Composable Megakernel Generator
//!
//! Generates model-specific megakernel MSL source at runtime from model metadata.
//! Instead of hand-written per-model kernel files, this module composes the kernel
//! from reusable building blocks based on the model's layer structure.
//!
//! Architecture:
//!   Model metadata (GGUF) → ModelDesc → composeMSL() → MSL source string
//!   Metal backend compiles the source at init via newLibraryWithSource.
//!
//! The generated kernel processes ALL layers in a single GPU dispatch using
//! atomic grid sync between stages. Building blocks from mega_common.metal
//! are referenced by the generated code (they're concatenated before it).

const std = @import("std");

/// Layer type for megakernel composition.
pub const LayerKind = enum {
    /// Standard GQA attention (Q/K/V projection, RoPE, SDPA, output projection).
    attention,
    /// DeltaNet SSM — breaks out of megakernel (sequential recurrence).
    deltanet,
    /// MoE expert routing — breaks out (CPU-side routing).
    moe,
    /// FFN-only (no attention, single up projection + activation + down).
    ffn_only,
};

/// Activation function for the FFN.
pub const Activation = enum {
    silu,
    gelu,
    relu_squared,
};

/// Quantization format for weight GEMV dispatch.
pub const QuantKind = enum {
    q8_0,
    q4_k,
    q5_k,
    q6_k,
    q4_0,
};

/// Maximum supported layers for static arrays.
const max_layers: usize = 64;

/// Model descriptor — everything needed to compose a megakernel.
/// Populated from GGUF/SafeTensors metadata at model init time.
pub const ModelDesc = struct {
    /// Model architecture name (for kernel function naming).
    name: []const u8,
    /// Number of transformer layers.
    n_layers: u32,
    /// Embedding dimension.
    n_embd: u32,
    /// FFN intermediate dimension (dense layers).
    n_ff: u32,
    /// Number of query heads.
    n_head: u32,
    /// Number of KV heads (for GQA).
    n_kv: u32,
    /// Per-head dimension.
    head_dim: u32,
    /// RoPE dimension (may be < head_dim for partial rotation).
    rope_dim: u32,
    /// RoPE base frequency.
    rope_theta: f32,
    /// RMS norm epsilon.
    rms_eps: f32,
    /// Maximum sequence length.
    max_seq_len: u32,
    /// FFN activation function.
    activation: Activation,
    /// Weight quantization format.
    quant: QuantKind,
    /// Per-layer type (attention, deltanet, moe, ffn_only).
    layer_types: [max_layers]LayerKind,

    // ── Model-specific flags ──────────────────────────────────
    /// Q projection includes interleaved gate (Qwen 3.5 only).
    has_gate: bool = false,
    /// Per-head Q/K RMS norms after projection.
    has_qk_norm: bool = false,
    /// Post-attention norm (fused addRmsNorm with FFN).
    has_post_attn_norm: bool = false,
    /// Fuse residual add into pre-norm (deferred residual pattern).
    fuse_residual: bool = false,

    /// Create a uniform layer pattern (all layers same type).
    pub fn uniform(n_layers: u32, kind: LayerKind) [max_layers]LayerKind {
        var types: [max_layers]LayerKind = undefined;
        for (0..max_layers) |i| {
            types[i] = if (i < n_layers) kind else .attention;
        }
        return types;
    }

    /// Create Qwen 3.5 hybrid pattern: DeltaNet except every Nth is attention.
    pub fn qwenHybrid(n_layers: u32, full_attn_interval: u32) [max_layers]LayerKind {
        var types: [max_layers]LayerKind = undefined;
        for (0..max_layers) |i| {
            if (i >= n_layers) {
                types[i] = .attention;
            } else if (full_attn_interval > 0 and ((i + 1) % full_attn_interval) == 0) {
                types[i] = .attention;
            } else {
                types[i] = .deltanet;
            }
        }
        return types;
    }
};

// ── MSL Template Fragments ───────────────────────────────────────────────
// These are composed into the final MSL source. Each fragment is a complete
// stage that calls the building blocks from mega_common.metal.

const msl_header =
    \\// Auto-composed megakernel — generated by mega_compose.zig
    \\// Single GPU dispatch for all layers. DO NOT EDIT.
    \\
    \\
;

/// Generate the params struct declaration.
fn emitParamsStruct(buf: []u8, desc: ModelDesc) []const u8 {
    return std.fmt.bufPrint(buf,
        \\struct MegaAutoParams {{
        \\    uint n_layers;
        \\    uint n_embd;
        \\    uint n_head;
        \\    uint n_kv;
        \\    uint head_dim;
        \\    uint n_ff;
        \\    uint rope_dim;
        \\    float rope_theta;
        \\    float rms_eps;
        \\    uint max_seq_len;
        \\    uint seq_pos;
        \\    uint n_tgs;
        \\}};
        \\
        \\
    , .{}) catch "";
    _ = desc;
}

/// GEMV function name for the given quant kind.
fn gemvFn(quant: QuantKind) []const u8 {
    return switch (quant) {
        .q8_0 => "mega_gemv_q8",
        .q4_k => "mega_gemv_q4k",
        .q5_k => "mega_gemv_q5k",
        .q6_k => "mega_gemv_q6k",
        .q4_0 => "mega_gemv_q4_0",
    };
}

/// Weight cast expression for typed vs raw pointers.
fn weightCast(quant: QuantKind) []const u8 {
    return switch (quant) {
        .q8_0 => "(device const block_q8_0*)(weights + lo.{s})",
        .q4_k, .q5_k, .q6_k => "weights + lo.{s}",
        .q4_0 => "(device const block_q4_0*)(weights + lo.{s})",
    };
}

/// Activation function call name.
fn activationFn(activation: Activation) []const u8 {
    return switch (activation) {
        .silu => "mega_silu_mul",
        .gelu => "mega_gelu_mul",
        .relu_squared => "mega_relu_squared",
    };
}

/// Compose a complete megakernel MSL source from a model descriptor.
/// The generated kernel is a single entry point that processes all layers.
/// Returns the generated MSL as a slice of the provided buffer.
pub fn composeMSL(buf: []u8, desc: ModelDesc) []const u8 {
    var pos: usize = 0;

    // Helper to append to buffer
    const append = struct {
        fn f(b: []u8, p: *usize, s: []const u8) void {
            if (p.* + s.len > b.len) return;
            @memcpy(b[p.*..][0..s.len], s);
            p.* += s.len;
        }
    }.f;

    // Header
    append(buf, &pos, msl_header);

    // Kernel signature
    const sig =
        \\kernel void megakernel_auto(
        \\    device const uchar*             weights     [[buffer(0)]],
        \\    device const MegaLayerOffsets*   layer_off   [[buffer(1)]],
        \\    device float*                    kv_keys     [[buffer(2)]],
        \\    device float*                    kv_values   [[buffer(3)]],
        \\    device float*                    hidden      [[buffer(4)]],
        \\    device float*                    scratch     [[buffer(5)]],
        \\    device atomic_uint*              sync_ctrs   [[buffer(6)]],
        \\    constant MegaAutoParams&         p           [[buffer(7)]],
        \\    uint tgid    [[threadgroup_position_in_grid]],
        \\    uint tid     [[thread_index_in_threadgroup]],
        \\    uint tg_size [[threads_per_threadgroup]])
        \\{
        \\    threadgroup float shared[8];
        \\    device float* hidden2    = scratch;
        \\    device float* ff_gate    = scratch + p.n_embd;
        \\    device float* ff_up      = scratch + p.n_embd + p.n_ff;
        \\    device float* qkv_buf    = scratch + p.n_embd + 2 * p.n_ff;
        \\    device float* ss_scratch = scratch + p.n_embd + 2 * p.n_ff +
        \\                               (p.n_head + 2 * p.n_kv) * p.head_dim;
        \\    uint sync_idx = 0;
        \\
        \\
    ;
    append(buf, &pos, sig);

    // Layer loop
    append(buf, &pos, "    for (uint li = 0; li < p.n_layers; li++) {\n");
    append(buf, &pos, "        device const MegaLayerOffsets& lo = layer_off[li];\n");

    // Pre-attention norm
    if (desc.fuse_residual) {
        append(buf, &pos,
            \\        device const float* norm_w = (device const float*)(weights + lo.attn_norm);
            \\        if (li > 0) {
            \\            mega_add_rms_norm(hidden, hidden2, norm_w, hidden2,
            \\                ss_scratch, &sync_ctrs[sync_idx++ % 32],
            \\                p.n_embd, p.n_tgs, p.rms_eps, shared, tgid, tid, tg_size);
            \\        } else {
            \\            mega_rms_norm(hidden, norm_w, hidden2,
            \\                ss_scratch, &sync_ctrs[sync_idx++ % 32],
            \\                p.n_embd, p.n_tgs, p.rms_eps, shared, tgid, tid, tg_size);
            \\        }
            \\
            \\
        );
    } else {
        append(buf, &pos,
            \\        device const float* norm_w = (device const float*)(weights + lo.attn_norm);
            \\        mega_rms_norm(hidden, norm_w, hidden2,
            \\            ss_scratch, &sync_ctrs[sync_idx++ % 32],
            \\            p.n_embd, p.n_tgs, p.rms_eps, shared, tgid, tid, tg_size);
            \\
            \\
        );
    }

    // Emit per-layer attention block for layers that have it
    // Check if any layers are attention
    var has_attn = false;
    for (0..desc.n_layers) |i| {
        if (desc.layer_types[i] == .attention) {
            has_attn = true;
            break;
        }
    }

    if (has_attn) {
        // Attention: Q/K/V GEMV → RoPE → KV append → SDPA → output
        const gemv = gemvFn(desc.quant);
        _ = gemv;

        // Use a runtime layer-type check since we can't comptime-unroll in MSL
        // The layer_types are encoded as a bitfield in the params or checked via
        // the weight offsets (attention layers have attn_q != 0)
        append(buf, &pos,
            \\        // Attention: skip if no attention weights for this layer
            \\        if (lo.attn_q != 0) {
            \\            uint qd = p.n_head * p.head_dim;
            \\            uint kvd = p.n_kv * p.head_dim;
            \\            device float* q_buf = qkv_buf;
            \\            device float* k_buf = qkv_buf + qd;
            \\            device float* v_buf = qkv_buf + qd + kvd;
            \\
            \\
        );

        // Q/K/V projections — emit with correct GEMV function
        const q_gemv = switch (desc.quant) {
            .q8_0 =>
            \\            mega_gemv_q8(hidden2, (device const block_q8_0*)(weights + lo.attn_q),
            \\                q_buf, qd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_k =>
            \\            mega_gemv_q4k(hidden2, weights + lo.attn_q,
            \\                q_buf, qd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q5_k =>
            \\            mega_gemv_q5k(hidden2, weights + lo.attn_q,
            \\                q_buf, qd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q6_k =>
            \\            mega_gemv_q6k(hidden2, weights + lo.attn_q,
            \\                q_buf, qd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_0 =>
            \\            mega_gemv_q4_0(hidden2, (device const block_q4_0*)(weights + lo.attn_q),
            \\                q_buf, qd, p.n_embd, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, q_gemv);
        append(buf, &pos, "\n            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");

        // K projection (same quant)
        const k_gemv = switch (desc.quant) {
            .q8_0 =>
            \\            mega_gemv_q8(hidden2, (device const block_q8_0*)(weights + lo.attn_k),
            \\                k_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_k =>
            \\            mega_gemv_q4k(hidden2, weights + lo.attn_k,
            \\                k_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q5_k =>
            \\            mega_gemv_q5k(hidden2, weights + lo.attn_k,
            \\                k_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q6_k =>
            \\            mega_gemv_q6k(hidden2, weights + lo.attn_k,
            \\                k_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_0 =>
            \\            mega_gemv_q4_0(hidden2, (device const block_q4_0*)(weights + lo.attn_k),
            \\                k_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, k_gemv);
        append(buf, &pos, "\n            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");

        // V projection
        const v_gemv = switch (desc.quant) {
            .q8_0 =>
            \\            mega_gemv_q8(hidden2, (device const block_q8_0*)(weights + lo.attn_v),
            \\                v_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_k =>
            \\            mega_gemv_q4k(hidden2, weights + lo.attn_v,
            \\                v_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q5_k =>
            \\            mega_gemv_q5k(hidden2, weights + lo.attn_v,
            \\                v_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q6_k =>
            \\            mega_gemv_q6k(hidden2, weights + lo.attn_v,
            \\                v_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_0 =>
            \\            mega_gemv_q4_0(hidden2, (device const block_q4_0*)(weights + lo.attn_v),
            \\                v_buf, kvd, p.n_embd, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, v_gemv);
        append(buf, &pos, "\n            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");

        // RoPE
        append(buf, &pos,
            \\            mega_rope(q_buf, p.n_head, p.head_dim, p.rope_dim, p.rope_theta, p.seq_pos,
            \\                tgid, tid, tg_size);
            \\            mega_rope(k_buf, p.n_kv, p.head_dim, p.rope_dim, p.rope_theta, p.seq_pos,
            \\                tgid, tid, tg_size);
            \\            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);
            \\            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);
            \\
            \\
        );

        // KV cache append + inline SDPA
        append(buf, &pos,
            \\            uint kv_layer_stride = p.max_seq_len * p.n_kv * p.head_dim;
            \\            device float* layer_keys = kv_keys + li * kv_layer_stride;
            \\            device float* layer_values = kv_values + li * kv_layer_stride;
            \\            mega_kv_append_f32(k_buf, v_buf, layer_keys, layer_values,
            \\                p.n_kv * p.head_dim, p.seq_pos, tgid, tid, tg_size);
            \\            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);
            \\            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);
            \\
            \\            device float* attn_out_buf = qkv_buf;
            \\            mega_sdpa_inline(q_buf, (device const uchar*)layer_keys,
            \\                (device const uchar*)layer_values, attn_out_buf,
            \\                p.n_head, p.n_kv, p.head_dim, p.seq_pos + 1,
            \\                1.0f / sqrt(float(p.head_dim)),
            \\                0, 0, 0, 0, shared, tgid, tid, tg_size);
            \\            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);
            \\            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);
            \\
            \\
        );

        // Output projection
        const out_gemv = switch (desc.quant) {
            .q8_0 =>
            \\            mega_gemv_q8(attn_out_buf, (device const block_q8_0*)(weights + lo.attn_output),
            \\                hidden2, p.n_embd, p.n_head * p.head_dim, shared, tgid, tid, tg_size);
            ,
            .q4_k =>
            \\            mega_gemv_q4k(attn_out_buf, weights + lo.attn_output,
            \\                hidden2, p.n_embd, p.n_head * p.head_dim, shared, tgid, tid, tg_size);
            ,
            .q5_k =>
            \\            mega_gemv_q5k(attn_out_buf, weights + lo.attn_output,
            \\                hidden2, p.n_embd, p.n_head * p.head_dim, shared, tgid, tid, tg_size);
            ,
            .q6_k =>
            \\            mega_gemv_q6k(attn_out_buf, weights + lo.attn_output,
            \\                hidden2, p.n_embd, p.n_head * p.head_dim, shared, tgid, tid, tg_size);
            ,
            .q4_0 =>
            \\            mega_gemv_q4_0(attn_out_buf, (device const block_q4_0*)(weights + lo.attn_output),
            \\                hidden2, p.n_embd, p.n_head * p.head_dim, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, out_gemv);
        append(buf, &pos, "\n            mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n            mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n");

        append(buf, &pos, "        }\n\n"); // close attention if
    }

    // Post-attention norm (if applicable)
    if (desc.has_post_attn_norm) {
        append(buf, &pos,
            \\        device const float* post_norm_w = (device const float*)(weights + lo.post_attn_norm);
            \\        mega_add_rms_norm(hidden, hidden2, post_norm_w, hidden2,
            \\            ss_scratch, &sync_ctrs[sync_idx++ % 32],
            \\            p.n_embd, p.n_tgs, p.rms_eps, shared, tgid, tid, tg_size);
            \\
            \\
        );
    } else {
        append(buf, &pos,
            \\        mega_add(hidden, hidden2, p.n_embd, tgid, tid, tg_size);
            \\        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);
            \\        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);
            \\
            \\
        );
    }

    // FFN: gate + up + activation + down
    if (desc.activation != .relu_squared) {
        // SwiGLU/GeGLU: gate + up GEMV → activation*mul → down GEMV
        const gate_gemv = switch (desc.quant) {
            .q8_0 =>
            \\        mega_gemv_q8(hidden2, (device const block_q8_0*)(weights + lo.ffn_gate),
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_k =>
            \\        mega_gemv_q4k(hidden2, weights + lo.ffn_gate,
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q5_k =>
            \\        mega_gemv_q5k(hidden2, weights + lo.ffn_gate,
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q6_k =>
            \\        mega_gemv_q6k(hidden2, weights + lo.ffn_gate,
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_0 =>
            \\        mega_gemv_q4_0(hidden2, (device const block_q4_0*)(weights + lo.ffn_gate),
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, gate_gemv);
        append(buf, &pos, "\n        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");

        // Up GEMV (same quant)
        const up_gemv = switch (desc.quant) {
            .q8_0 =>
            \\        mega_gemv_q8(hidden2, (device const block_q8_0*)(weights + lo.ffn_up),
            \\            ff_up, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_k =>
            \\        mega_gemv_q4k(hidden2, weights + lo.ffn_up,
            \\            ff_up, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q5_k =>
            \\        mega_gemv_q5k(hidden2, weights + lo.ffn_up,
            \\            ff_up, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q6_k =>
            \\        mega_gemv_q6k(hidden2, weights + lo.ffn_up,
            \\            ff_up, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            .q4_0 =>
            \\        mega_gemv_q4_0(hidden2, (device const block_q4_0*)(weights + lo.ffn_up),
            \\            ff_up, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, up_gemv);
        append(buf, &pos, "\n        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");

        // Activation
        const act_call = switch (desc.activation) {
            .silu => "        mega_silu_mul(ff_gate, ff_up, p.n_ff, tgid, tid, tg_size);\n",
            .gelu => "        mega_gelu_mul(ff_gate, ff_up, p.n_ff, tgid, tid, tg_size);\n",
            .relu_squared => unreachable,
        };
        append(buf, &pos, act_call);
        append(buf, &pos, "        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");
    } else {
        // ReLU²: single up GEMV → relu² → down
        const up_gemv = switch (desc.quant) {
            .q8_0 =>
            \\        mega_gemv_q8(hidden2, (device const block_q8_0*)(weights + lo.ffn_up),
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
            else =>
            \\        mega_gemv_q4k(hidden2, weights + lo.ffn_up,
            \\            ff_gate, p.n_ff, p.n_embd, shared, tgid, tid, tg_size);
            ,
        };
        append(buf, &pos, up_gemv);
        append(buf, &pos, "\n        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n");
        append(buf, &pos, "        mega_relu_squared(ff_gate, p.n_ff, tgid, tid, tg_size);\n");
        append(buf, &pos, "        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n\n");
    }

    // Down projection
    const down_gemv = switch (desc.quant) {
        .q8_0 =>
        \\        mega_gemv_q8(ff_gate, (device const block_q8_0*)(weights + lo.ffn_down),
        \\            hidden2, p.n_embd, p.n_ff, shared, tgid, tid, tg_size);
        ,
        .q4_k =>
        \\        mega_gemv_q4k(ff_gate, weights + lo.ffn_down,
        \\            hidden2, p.n_embd, p.n_ff, shared, tgid, tid, tg_size);
        ,
        .q5_k =>
        \\        mega_gemv_q5k(ff_gate, weights + lo.ffn_down,
        \\            hidden2, p.n_embd, p.n_ff, shared, tgid, tid, tg_size);
        ,
        .q6_k =>
        \\        mega_gemv_q6k(ff_gate, weights + lo.ffn_down,
        \\            hidden2, p.n_embd, p.n_ff, shared, tgid, tid, tg_size);
        ,
        .q4_0 =>
        \\        mega_gemv_q4_0(ff_gate, (device const block_q4_0*)(weights + lo.ffn_down),
        \\            hidden2, p.n_embd, p.n_ff, shared, tgid, tid, tg_size);
        ,
    };
    append(buf, &pos, down_gemv);
    append(buf, &pos, "\n        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n");

    // End of layer loop
    if (!desc.fuse_residual) {
        append(buf, &pos, "\n        mega_add(hidden, hidden2, p.n_embd, tgid, tid, tg_size);\n");
        append(buf, &pos, "        mega_grid_sync(&sync_ctrs[sync_idx++ % 32], p.n_tgs, tgid, tid);\n        mega_sync_reset(&sync_ctrs[(sync_idx-1) % 32], tgid, tid);\n");
    }
    append(buf, &pos, "    }\n");

    // Final residual (for fused residual models)
    if (desc.fuse_residual) {
        append(buf, &pos, "    mega_add(hidden, hidden2, p.n_embd, tgid, tid, tg_size);\n");
    }

    // Close kernel
    append(buf, &pos, "}\n");

    return buf[0..pos];
}

// ── Tests ────────────────────────────────────────────────────────────────

test "composeMSL generates valid kernel for Gemma Q4_K" {
    var buf: [32768]u8 = undefined;
    const desc = ModelDesc{
        .name = "gemma",
        .n_layers = 28,
        .n_embd = 2304,
        .n_ff = 9216,
        .n_head = 8,
        .n_kv = 4,
        .head_dim = 256,
        .rope_dim = 256,
        .rope_theta = 10000.0,
        .rms_eps = 1e-6,
        .max_seq_len = 4096,
        .activation = .gelu,
        .quant = .q4_k,
        .layer_types = ModelDesc.uniform(28, .attention),
    };
    const msl = composeMSL(&buf, desc);
    // Should contain the kernel entry point
    try std.testing.expect(std.mem.indexOf(u8, msl, "kernel void megakernel_auto") != null);
    // Should contain GELU activation
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_gelu_mul") != null);
    // Should contain Q4_K GEMV
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_gemv_q4k") != null);
    // Should contain SDPA
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_sdpa_inline") != null);
}

test "composeMSL generates Qwen SiLU with fused residual" {
    var buf: [32768]u8 = undefined;
    const desc = ModelDesc{
        .name = "qwen35",
        .n_layers = 24,
        .n_embd = 1536,
        .n_ff = 4096,
        .n_head = 16,
        .n_kv = 4,
        .head_dim = 128,
        .rope_dim = 64,
        .rope_theta = 10000000.0,
        .rms_eps = 1e-6,
        .max_seq_len = 4096,
        .activation = .silu,
        .quant = .q8_0,
        .has_post_attn_norm = true,
        .fuse_residual = true,
        .layer_types = ModelDesc.qwenHybrid(24, 4),
    };
    const msl = composeMSL(&buf, desc);
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_silu_mul") != null);
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_add_rms_norm") != null);
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_gemv_q8") != null);
}

test "composeMSL generates Nemotron-H ReLU² FFN" {
    var buf: [32768]u8 = undefined;
    var layer_types: [max_layers]LayerKind = undefined;
    for (0..42) |i| layer_types[i] = .ffn_only;
    layer_types[5] = .attention;
    layer_types[12] = .attention;

    const desc = ModelDesc{
        .name = "nemotron_h",
        .n_layers = 42,
        .n_embd = 3136,
        .n_ff = 12544,
        .n_head = 40,
        .n_kv = 8,
        .head_dim = 128,
        .rope_dim = 78,
        .rope_theta = 10000.0,
        .rms_eps = 1e-6,
        .max_seq_len = 4096,
        .activation = .relu_squared,
        .quant = .q8_0,
        .layer_types = layer_types,
    };
    const msl = composeMSL(&buf, desc);
    try std.testing.expect(std.mem.indexOf(u8, msl, "mega_relu_squared") != null);
}
