#!/usr/bin/env bash
# Regenerate man/agave.1 from the CLI's own help text.
# Canonical: bash scripts/gen-manpage.sh   (run after editing usage_text in src/main.zig)
#
# A man page transcribed by hand is a second copy of the flag list, and the two
# copies disagree as soon as a flag is added. usage_text in src/main.zig is what
# `agave --help` prints and what a test already pins against cli_specs, so the
# man page is rendered from it rather than written next to it. Regenerate
# instead of editing man/agave.1; the drift test in src/main.zig fails when the
# two are out of step.
set -euo pipefail
export LC_ALL=C TZ=UTC

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

out=man/agave.1
src=src/main.zig

# The value supported_arch_help computes. It is built by a comptime block, not
# a literal, so it cannot be read back the way repl_help is; a test in
# src/main.zig pins this same string, so the block changing fails there first.
readonly ARCH_LIST="gemma3, gemma4, diffusion-gemma, qwen35, qwen4exp, qwen4-exp, gpt-oss, nemotron-h, nemotron-nano, glm4, deepseek4, llama4"

# A multiline string literal: one `\\`-prefixed source line per output line,
# from `const NAME =` to ENDLINE inclusive, with the delimiters dropped.
literal_lines() {
    sed -n "/^const $1 =\$/,/^$2\$/p" "$src" |
        sed -e '1d' -e '$d' -e 's/^    \\\\/ /' -e 's/^    \\$/ /'
}

version="$(sed -n 's/^[[:space:]]*\.version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' build.zig.zon | head -n1)"
if [[ -z "$version" ]]; then
    echo "gen-manpage: could not read .version from build.zig.zon" >&2
    exit 1
fi

repl_help=""
repl_help="$(literal_lines repl_help ';')"

help_body="$(literal_lines usage_text '++ repl_help;')"
if [[ -z "$help_body" ]]; then
    echo "gen-manpage: extracted no usage_text from $src" >&2
    exit 1
fi

mkdir -p man
{
    cat <<EOF
.\" Generated by scripts/gen-manpage.sh from usage_text in src/main.zig.
.\" Do not edit by hand: run \`bash scripts/gen-manpage.sh\`.
.TH AGAVE 1 "" "agave $version" "User Commands"
.SH NAME
agave \\- Zig LLM inference engine
.SH SYNOPSIS
.B agave
[\\fIOPTIONS\\fR] \\fIMODEL\\fR[\\fI.PROMPT\\fR]
.B agave
[\\fIOPTIONS\\fR] \\fBpull\\fR \\fIORG/REPO\\fR
.B agave
[\\fIOPTIONS\\fR] \\fBcalibrate\\fR \\fIMODEL\\fR
.SH DESCRIPTION
Loads a GGUF model or a SafeTensors directory and generates text, or serves an
OpenAI- and Anthropic-compatible HTTP API. The options, environment, and
examples below are the output of \`agave --help\`.
.SS Options, environment, and examples
.nf
EOF
    # roff reads a backslash as an escape and a line opening with `.` or `'`
    # as a request; the help text contains both. The block is a literal
    # (\fBnf\fR) so the two-column layout survives instead of being refilled.
    printf '%s\n' "$help_body" |
        sed -e 's/\\/\\e/g' -e "s/^\\([.']\\)/\\\\&\\1/" |
        sed -e "s|^++ supported_arch_help ++\$|  $ARCH_LIST|"
    printf '%s\n' "$repl_help"
    cat <<'EOF'
.fi
.SH FILES
.TP
$XDG_CACHE_HOME/agave/conversations.json
Web-UI conversation store (\fI--conv-store\fR). Falls back to
$HOME/.cache/agave/conversations.json.
.TP
$HOME/.cache/huggingface
Model blobs downloaded by `agave pull` (\fIHF_HOME\fR overrides the base).
.SH "EXIT STATUS"
.TP
.B 0
Success.
.TP
.B 1
Runtime failure: model load, inference, or a failed operation.
.TP
.B 2
Invalid command line: unknown flag, missing value, or an out-of-range value.
.SH "SEE ALSO"
Project documentation: https://github.com/maci0/agave
.SH COPYRIGHT
GPL-3.0-or-later. The full text ships alongside the binary as
/usr/share/doc/agave/copyright.
EOF
} >"$out"

echo "gen-manpage: wrote $out (agave $version)"
